- hosts: localhost
  gather_facts: yes
  vars_files:
    - ../vars/container.yml
  
  tasks:
    - name: Build docker image
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        build:
          path: "{{ project_root_path }}"
          dockerfile: "{{docker_file_path}}/Dockerfile"
        source: build
    
    - name: Push docker image to registry
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local
    
    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{image_name}}:{{image_tag}}"
        state: started
        recreate: true
        published_ports:
          - "{{ listen_port }}:3000"