name: Code quality pipeline

on:
  push:
    branches:
      - pipeline_practice

jobs:
    quiality:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install depencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint black
                pip install -r requirements.txt
            - name: Check EditorConfig
              uses: editorconfig-checker/action-editorconfig-checker@v2 
            - name: Lint code
              run: pylint --disable=C0111,C0114,C0115,C0116 $(git ls-files '*.py')