name: Code quality pipeline

on:
  push:
    branches:
      - pipeline_practice

jobs:
    checkout_code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
    install_dependencies:
        needs: checkout_code
        runs-on: ubuntu-latest
        steps:
            - name: Install depencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
    check_editorconfig:
        needs: checkout_code
        runs-on: ubuntu-latest
        steps:
            - uses: editorconfig-checker/action-editorconfig-checker@v2
            - run: editorconfig-checker
    quiality:
        needs: [checkout_code, install_dependencies]
        runs-on: ubuntu-latest
        steps:
            - name: Lint code
              run: pylint --disable=C0111,C0114,C0115,C0116 $(git ls-files '*.py')