name: Code quality pipeline

on:
  push:
    branches:
      - pipeline_practice

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'

            - name: Cache pip packages
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint black
                pip install -r requirements.txt

    check_editorconfig:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: editorconfig-checker/action-editorconfig-checker@v2
            - run: editorconfig-checker

    lint:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - name: Cache pip packages
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: Install dependencies  # Will be fast due to cache
              run: |
                python -m pip install --upgrade pip
                pip install pylint
            - name: Run pylint
              run: pylint --disable=C0111,C0114,C0115,C0116 $(git ls-files '*.py')

    format:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - name: Cache pip packages
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: Install dependencies  # Will be fast due to cache
              run: |
                python -m pip install --upgrade pip
                pip install black
            - name: Run black
              run: black . --check

    check_markdown:
      needs: setup
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '16'
          - name: Install markdownlint-cli
            run: npm install -g markdownlint-cli
          - name: Create markdownlint config
            run: |
              echo '{
                "MD013": false,
                "line-length": false
              }' > .markdownlint.json
          - name: Run markdown lint
            run: markdownlint '**/*.md' --ignore node_modules
    
    unit_test:
      needs: [setup, lint]
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.x'
          - name: Cache pip packages
            uses: actions/cache@v3
            with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-pip-
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
          - name: Run tests
            run: |
              cd app  # Change to app directory
              python -m unittest app_test.py

    check_secrets:
      needs: unit_test
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0  # Required to scan all commits
          - name: Gitleaks scan
            uses: gitleaks/gitleaks-action@v2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
