name: Code quality pipeline

on:
  push:
    branches:
      - pipeline_practice

jobs:
    quiality:
        runs-on: ubuntu-latest
        steps:
            - name: Install depencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint black
            - name: Check if .editorconfig exists
              if: ${{ !hashFiles('.editorconfig') != '' }}
              run: echo "Editorconfig file exists"
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Lint code
              run: pylint $(git ls-files '*.py')